print('{:=^30}\n'.format(str(' Exercício 009 ')))
#------------------------------------------------
x = int(input('Digite um número para efetuar sua tabuada: '))
#------------------------------------------------
print('\n------------------')
print('| 1 |x| {} |= {} |'.format(x, (x*1)))
print('------------------')
print('| 2 |x| {} |= {} |'.format(x, (x*2)))
print('------------------')
print('| 3 |x| {} |= {} |'.format(x, (x*3)))
print('------------------')
print('| 4 |x| {} |= {} |'.format(x, (x*4)))
print('------------------')
print('| 5 |x| {} |= {} |'.format(x, (x*5)))
print('------------------')
print('| 6 |x| {} |= {} |'.format(x, (x*6)))
print('------------------')
print('| 7 |x| {} |= {} |'.format(x, (x*7)))
print('------------------')
print('| 8 |x| {} |= {} |'.format(x, (x*8)))
print('------------------')
print('| 9 |x| {} |= {} |'.format(x, (x*9)))
print('------------------')
print('| 10|x| {} |= {} |'.format(x, (x*10)))
print('------------------')